FROM node:20-alpine

WORKDIR /app

# Install dependencies FIRST to leverage Docker cache
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# NestJS watch mode
CMD ["npm", "run", "start:dev"]
