FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Angular CLI needs 0.0.0.0 to be accessible from host
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]
