FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Angular CLI handles SSR in dev mode with ng serve
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4300"]
